sun-dragon-cult/fvtt-system-rqg

src/actors/sheet-parts/gear-tab.hbs
src/rqg.scss

div needed style="display: block"

bug combat rows don't align Fixes #108

---

snowpack.config.js
src/actors/rqgActorSheet.ts
src/actors/sheet-parts/gear-tab.hbs
src/i18n/en.json
src/rqg.scss
src/system/registerHandlebarsHelpers.ts

Fixes #96
- added column with extended value of coins
- created new "currency" grid class with 8 columns
- applied text-right to the quantity textbox

feat Calc total worth in currency item

---

src/chat/weaponCard.ts

- fixed the logic error
- provided better message for using your last ammo
- provided better message for not having the ammo to shoot
- This raises questions about pluralizing items that should be addressed in another issue.

bug Fixed out of ammo if quantity === 1, issue #111

---

src/dialog/improveAbilityDialog.ts
src/i18n/en.json
src/items/RqgItemSheet.ts
src/items/cult-item/cultSheet.ts
src/items/rune-item/runeSheet.ts
src/items/rune-magic-item/runeMagicSheet.ts
src/items/skill-item/skillSheet.ts
src/items/spirit-magic-item/spiritMagicSheet.ts
src/system/util.ts

Fixes #166
- added _onDrop to RqgItemSheet.ts
- add localizeItemType to util.ts
- used localizeItemType in title of RqgItemSheet.ts
- used localizeItemType in improveAbilityDialog.ts
- sorted ITEM types in en.json
- added Shamanicability to ITEM in en.json
- added Sorcerymagic to ITEM in en.json
- removed _onDrop from cultSheet.ts, runeSheet.ts, runeMagicSheet.ts, skillSheet.ts, and spiritMagicSheet.ts

bug Spirit Magic Sheet not persisting journal links

---

src/chat/runeMagicCard.ts

bug Rune Spell with rune the actor does not have causes an error #191

---

src/items/hit-location-item/hitLocationSheet.ts

Fixes #183
- Ensure that only one of "dead", "unconscious", or "shocked" will be displayed as a status.

bug Healing Duplicates Status Effect

---

src/items/RqgItemSheet.ts
src/items/rqgItem.ts
src/system/util.ts

Fixes #215
- if rqid parameter is undefined or empty return undefined
- Don't warn about not finding an item in getItemFromWorldByRqid.  Only warn if nothing is found after checking the world and the comendia
- removed extraneous console.log
fixed issues found after approving merge to #199

getItemByRqid follow up

---

src/items/spirit-magic-item/spiritMagicSheet.hbs

Fixes #220
- input had 'name="data.name"' but needed 'name="name"'

Spirit Magic Sheet Name not updating item

---

src/actors/rqgActor.ts
src/actors/rqgActorCreationSheet.hbs
src/actors/rqgActorCreationSheet.ts
src/i18n/en.json
src/rqg.scss
src/system/registerHandlebarsHelpers.ts

Fixes #229
- Added rqgActorCreation sheet

#101 Subtask: Alternate Actor Sheet

---

src/actors/rqgActorSheet.ts
src/dialog/actorWizardApplication.hbs
src/dialog/actorWizardApplication.ts
src/i18n/en.json
src/rqg.scss
src/system/config.ts
src/system/registerHandlebarsHelpers.ts

Fixes #246
- added actorWizardApplication.ts and actorWizardApplication.hbs
- added header button to actor sheet to launch actor wizard
- added sheet-button class
- added creation-sheet-tabs class
- added flagScope to config
- added actorWizardFlags to config
- added colonBreak handlebar helper

#101 Subtask: Actor Wizard FormApplication Framework

---

src/system/migrations/migrateWorld.ts
src/system/migrations/migrations-item/renameDragonewt.ts

svg file is already renamed in 063072a01e5c20ee64c3b946d060ef1b4569e3a3

chore: migrate rune Dragonnewt to Dragonewt

---

src/i18n/en.json
src/rqg.ts
src/system/migrations/applyMigrations.ts
src/system/migrations/migrations-actor/migrateActorDummy.ts
src/system/migrations/migrations-item/migrateItemDummy.ts

also updated references from `pack.metadata.entity` to `pack.metadata.type`

feat: improve migration progress feedback

---

src/data-model/shared/rqidLink.ts
src/dialog/actorWizardApplication.ts
src/i18n/en.json
src/rqg.ts
src/system/api/nameGeneration.ts
src/system/api/rqidApi.ts
src/system/config.ts
src/system/migrations/migrations-item/renameDragonewt.ts
src/system/util.ts

also uses that index to improve speed of `fromRqid` and generalise the rqidApi to work with most document types.

feat: Include rqid in compendium index

---

src/system/api/rqidApi.ts

Apparently I did this for the compendium search, but not for the world search...

fix: fromRqid does not return the "best" document from the world

---

src/assets/compendiums/demo-actors.db/adventurer.yaml
src/assets/compendiums/demo-actors.db/spirit.yaml
src/assets/compendiums/demo-items.db/demo-items.yaml
src/assets/compendiums/homelands.db/sartar-colymar-tribal-lands.yaml
src/assets/compendiums/skills-basic.db/agility.yaml
src/assets/compendiums/skills-basic.db/communication.yaml
src/assets/compendiums/skills-basic.db/knowledge.yaml
src/assets/compendiums/skills-basic.db/magic.yaml
src/assets/compendiums/skills-basic.db/manipulation.yaml
src/assets/compendiums/skills-basic.db/perception.yaml
src/assets/compendiums/skills-basic.db/stealth.yaml
src/assets/compendiums/skills-profession.db/communication.yaml
src/assets/compendiums/skills-profession.db/knowledge.yaml
src/assets/compendiums/skills-profession.db/magic.yaml
src/assets/compendiums/species-templates.db/human.yaml
src/items/skill-item/skillSheet.ts
src/mocks/mockActor.ts
src/system/config.ts
src/system/migrations/migrateWorld.ts
src/system/migrations/migrations-item/trimCategoryFromSkillNames.ts

- Skill category no longer used when creating the name for a skill
- All existing skill references also have their skill categories removed

removing skill categories

---

src/assets/pack-templates/skill-descriptions/agility.yaml
src/assets/pack-templates/skill-descriptions/communication.yaml
src/assets/pack-templates/skill-descriptions/knowledge.yaml
src/assets/pack-templates/skill-descriptions/magic.yaml
src/assets/pack-templates/skill-descriptions/manipulation.yaml
src/assets/pack-templates/skill-descriptions/perception.yaml
src/assets/pack-templates/skill-descriptions/stealth.yaml
src/assets/pack-templates/skill-descriptions/weapon.yaml
src/i18n/en/openSystem.json
src/system.json

Skill descriptions copied from the RQ starter Set module and moving in.
Changed references to always use the OpenSystem prio and lang

feat: Adding skill descriptions to the RQ System

---

src/assets/pack-templates/skills-weapons/1h-axe.yaml
src/assets/pack-templates/skills-weapons/1h-dagger.yaml
src/assets/pack-templates/skills-weapons/1h-fist.yaml
src/assets/pack-templates/skills-weapons/1h-hammer.yaml
src/assets/pack-templates/skills-weapons/1h-mace.yaml
src/assets/pack-templates/skills-weapons/1h-spear.yaml
src/assets/pack-templates/skills-weapons/1h-sword.yaml
src/assets/pack-templates/skills-weapons/2h-melee.yaml
src/assets/pack-templates/skills-weapons/missile.yaml
src/assets/pack-templates/skills-weapons/natural.yaml
src/assets/pack-templates/skills-weapons/shields.yaml
src/system.json

Added weapon skills to the system and updating references to the SS json to the openSystem json. Also removed all of the _id values.

Adding weapon skills

---

src/actors/context-menus/passion-context-menu.ts
src/actors/rqgActorSheet.ts
src/actors/sheet-parts/passions-tab.hbs
src/i18n/en/openSystem.json

Added a "+" button on the Passions tab of the Actor sheet that creates a new Passion on the Actor.  Also allow players to delete Passions via the context menu.

feat: allow players to add Passions

---

src/combat/rqgToken.ts

feat: initialize Actor for new Token if Actor is unlinked

---

src/assets/pack-templates/skills-weapons/1h-axe.yaml
src/assets/pack-templates/skills-weapons/1h-dagger.yaml
src/assets/pack-templates/skills-weapons/1h-fist.yaml
src/assets/pack-templates/skills-weapons/1h-hammer.yaml
src/assets/pack-templates/skills-weapons/1h-mace.yaml
src/assets/pack-templates/skills-weapons/1h-spear.yaml
src/assets/pack-templates/skills-weapons/1h-sword.yaml
src/assets/pack-templates/skills-weapons/2h-melee.yaml
src/assets/pack-templates/skills-weapons/missile.yaml
src/assets/pack-templates/skills-weapons/natural.yaml
src/assets/pack-templates/skills-weapons/shields.yaml
src/assets/pack-templates/skills/knowledge-skills.yaml

fix: skill Base Chances

---

src/actors/context-menus/characteristic-context-menu.ts
src/actors/context-menus/contextMenuRunes.ts
src/i18n/en/openSystem.json

feat: initialize Characteristics to Average Value

---

src/actors/context-menus/characteristic-context-menu.ts
src/combat/rqgToken.ts

feat: silent Initialize All Characteristics for GM

---

src/actors/_actorsheets.scss
src/actors/rqgActorSheet.hbs
src/actors/rqgActorSheet.ts

feat: evaluate Initialized Characteristics

---

src/assets/pack-templates/equipment-weapons/axes.yaml
src/assets/pack-templates/equipment-weapons/bows-crossbows.yaml
src/assets/pack-templates/equipment-weapons/hammers-maces-clubs.yaml
src/assets/pack-templates/equipment-weapons/javelins-spears-darts.yaml
src/assets/pack-templates/equipment-weapons/pole-weapons.yaml
src/assets/pack-templates/equipment-weapons/shield.yaml
src/assets/pack-templates/equipment-weapons/slings.yaml
src/assets/pack-templates/equipment-weapons/spears.yaml
src/assets/pack-templates/equipment-weapons/swords-daggers.yaml
src/assets/pack-templates/equipment-weapons/thrown-weapons.yaml
src/assets/pack-templates/equipment-weapons/unarmed-attacks.yaml

fix: add skillId to weapons

---

src/system.json

fix: system background is broken

---

src/chat/RqgChatMessage.ts

fix: can only add one digit at a time to Modifiers box
